apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: app
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: 962215205296.dkr.ecr.sa-east-1.amazonaws.com/vivo-api-gateway:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-gateway
                  key: DATABASE_URL
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway
                  key: ELASTIC_APM_SERVER_URL
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-gateway
                  key: ELASTIC_APM_SECRET_TOKEN
            - name: ELASTIC_APM_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-gateway
                  key: ELASTIC_APM_SERVICE_NAME
            - name: ELASTIC_APM_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: api-gateway
                  key: ELASTIC_APM_ENVIRONMENT
            - name: QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway
                  key: QUEUE_URL
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: api-gateway
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: api-gateway
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: api-gateway
                  key: AWS_SECRET_ACCESS_KEY
            - name: EXTERNAL_API_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway
                  key: EXTERNAL_API_URL
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway
  namespace: app
data:
  ELASTIC_APM_SERVER_URL: http://apm-server-apm-server.monitoring.svc.cluster.local:8200
  ELASTIC_APM_SERVICE_NAME: api-gateway
  ELASTIC_APM_ENVIRONMENT: production
  QUEUE_URL: https://sqs.sa-east-1.amazonaws.com/962215205296/vivo-invalidation-queue
  AWS_REGION: sa-east-1
  EXTERNAL_API_URL: http://external-api.app.svc.cluster.local:80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.vivo.bouasli.com
      secretName: tls-secret
  rules:
    - host: api.vivo.bouasli.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80