apiVersion: v1
kind: Service
metadata:
  name: external-api
  namespace: app
spec:
  selector:
    app: external-api
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-api
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-api
  template:
    metadata:
      labels:
        app: external-api
    spec:
      containers:
        - name: external-api
          image: 962215205296.dkr.ecr.sa-east-1.amazonaws.com/vivo-external-api:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: external-api
                  key: DATABASE_URL
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: external-api
                  key: ELASTIC_APM_SERVER_URL
            - name: ELASTIC_APM_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: external-api
                  key: ELASTIC_APM_SERVICE_NAME
            - name: ELASTIC_APM_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: external-api
                  key: ELASTIC_APM_ENVIRONMENT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: external-api
                  key: JWT_SECRET
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: external-api
                  key: ELASTIC_APM_SECRET_TOKEN
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-api
  namespace: app
data:
  ELASTIC_APM_SERVER_URL: http://apm-server-apm-server.monitoring.svc.cluster.local:8200
  ELASTIC_APM_SERVICE_NAME: external-api
  ELASTIC_APM_ENVIRONMENT: production